# Generated by Django 5.0.7 on 2024-12-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=100)),
                ('course_subtitle', models.CharField(max_length=100)),
                ('course_description', models.TextField()),
                ('course_bullets', models.TextField()),
            ],
        ),
    ]
